name: TEPIC
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _r-mutex
  - bedtools
  - binutils
  - binutils_impl_linux-64
  - binutils_linux-64
  - bwidget
  - bzip2
  - c-ares
  - c-compiler
  - ca-certificates
  - cairo
  - certifi
  - compilers
  - curl
  - cxx-compiler
  - fontconfig
  - fortran-compiler
  - freetype
  - fribidi
  - gcc_impl_linux-64
  - gcc_linux-64
  - gettext
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - graphite2
  - gsl
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - icu
  - jpeg
  - kernel-headers_linux-64
  - krb5
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libcurl
  - libedit
  - libev
  - libffi
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libssh2
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - lz4-c
  - make
  - ncurses
  - numpy
  - openssl
  - pango
  - pcre
  - pcre2
  - pip
  - pixman
  - python
  - python_abi
  - r-assertthat
  - r-backports
  - r-base
  - r-bitops
  - r-brio
  - r-callr
  - r-catools
  - r-cli
  - r-codetools
  - r-colorspace
  - r-crayon
  - r-desc
  - r-diffobj
  - r-digest
  - r-domc
  - r-ellipsis
  - r-evaluate
  - r-fansi
  - r-farver
  - r-foreach
  - r-gdata
  - r-ggplot2
  - r-glmnet
  - r-glue
  - r-gplots
  - r-gridextra
  - r-gtable
  - r-gtools
  - r-isoband
  - r-iterators
  - r-jsonlite
  - r-kernsmooth
  - r-labeling
  - r-lattice
  - r-lifecycle
  - r-magrittr
  - r-mass
  - r-matrix
  - r-mgcv
  - r-munsell
  - r-nlme
  - r-pillar
  - r-pkgbuild
  - r-pkgconfig
  - r-pkgload
  - r-plyr
  - r-praise
  - r-prettyunits
  - r-processx
  - r-ps
  - r-r6
  - r-rcolorbrewer
  - r-rcpp
  - r-rematch2
  - r-reshape2
  - r-rlang
  - r-rprojroot
  - r-rstudioapi
  - r-scales
  - r-shape
  - r-stringi
  - r-stringr
  - r-survival
  - r-testthat
  - r-tibble
  - r-utf8
  - r-vctrs
  - r-viridislite
  - r-waldo
  - r-withr
  - r-zeallot
  - readline
  - scipy
  - sed
  - setuptools
  - sqlite
  - sysroot_linux-64
  - tk
  - tktable
  - twobitreader
  - tzdata
  - wheel
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd