contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #inspect channel"
    url: https://nfcore.slack.com/channels/inspect
    about: Discussion about the nf-core/inspect pipeline
