contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #tfprio channel"
    url: https://nfcore.slack.com/channels/tfprio
    about: Discussion about the nf-core/tfprio pipeline
